import os
import numpy as np
import matplotlib.pyplot as plt

x=np.linspace(0,40,40)
plt.figure()
data = np.loadtxt("grafica.dat")
plt.subplot(3,2,1)
plt.plot(x,data[:40,0])
plt.xlabel('X')
plt.ylabel('Y')
plt.subplot(3,2,2)
plt.plot(x,data[:40,1])
plt.xlabel('X')
plt.ylabel('Y')
plt.subplot(3,2,3)
plt.plot(x,data[:40,2])
plt.xlabel('X')
plt.ylabel('Y')
plt.subplot(3,2,4)
plt.plot(x,data[40:80,0])
plt.xlabel('X')
plt.ylabel('Y')
plt.subplot(3,2,5)
plt.plot(x,data[40:80,1])
plt.xlabel('X')
plt.ylabel('Y')
plt.subplot(3,2,6)
plt.plot(x,data[40:80,2])
plt.xlabel('X')
plt.ylabel('Y')
plt.savefig("primer orden.png")